
export const products = [
      {
        id: 1,
        name: '19mm Silk Duvet',
        slug: '19mm-silk-duvet',
        description: 'Luxury mulberry silk duvet for all seasons',
        image: '/images/products/duvet-1.jpg',
        price: 299,
        categories: ['all-season', 'hotel'],
      },
      {
        id: 2,
        name: 'Silk Pillowcase Set',
        slug: 'silk-pillowcase-set',
        description: 'Set of 2 pure silk pillowcases',
        image: '/images/products/pillowcase-1.jpg',
        price: 89,
        categories: ['all-season'],
      },
      {
        id: 3,
        name: 'Winter Silk Comforter',
        slug: 'winter-silk-comforter',
        description: 'Extra warm silk comforter for winter',
        image: '/images/products/comforter-1.jpg',
        price: 399,
        categories: ['winter'],
      },
      {
        id: 4,
        name: 'Summer Weight Silk Blanket',
        slug: 'summer-weight-silk-blanket',
        description: 'Lightweight silk blanket for summer nights',
        image: '/images/products/blanket-1.jpg',
        price: 199,
        categories: ['summer'],
      },
      {
        id: 5,
        name: 'Kids Silk Bedding Set',
        slug: 'kids-silk-bedding-set',
        description: 'Colorful silk bedding set for children',
        image: '/images/products/kids-1.jpg',
        price: 159,
        categories: ['children'],
      },
      {
        id: 6,
        name: 'Organic Silk Sheet Set',
        slug: 'organic-silk-sheet-set',
        description: 'GOTS certified organic silk sheets',
        image: '/images/products/organic-1.jpg',
        price: 259,
        categories: ['organic'],
      },
      {
        id: 7,
        name: 'Hotel Collection Duvet',
        slug: 'hotel-collection-duvet',
        description: 'Premium hotel quality silk duvet',
        image: '/images/products/hotel-1.jpg',
        price: 499,
        categories: ['hotel'],
      },
      {
        id: 8,
        name: 'Summer Silk Throw',
        slug: 'summer-silk-throw',
        description: 'Light silk throw for summer evenings',
        image: '/images/products/throw-1.jpg',
        price: 129,
        categories: ['summer'],
      }
    ]