export const products = [
      {
        id: 1,
        title: '19mm Silk Duvet',
        href: '19mm-silk-duvet',
        description: 'Luxury mulberry silk duvet for all seasons',
        image: '/images/allseason.webp',
        categories: ['all-season', 'hotel'],
      },
      {
        id: 2,
        title: 'Silk Pillowcase Set',
        href: 'silk-pillowcase-set',
        description: 'Set of 2 pure silk pillowcases',
        image: '/images/products/pillowcase-1.jpg',
        categories: ['all-season'],
      },
      {
        id: 3,
        title: 'Winter Silk Comforter',
        href: 'winter-silk-comforter',
        description: 'Extra warm silk comforter for winter',
        image: '/images/products/comforter-1.jpg',
        categories: ['winter'],
      },
      {
        id: 4,
        title: 'Summer Weight Silk Blanket',
        href: 'summer-weight-silk-blanket',
        description: 'Lightweight silk blanket for summer nights',
        image: '/images/products/blanket-1.jpg',
        categories: ['summer'],
      },
      {
        id: 5,
        title: 'Kids Silk Bedding Set',
        href: 'kids-silk-bedding-set',
        description: 'Colorful silk bedding set for children',
        image: '/images/products/kids-1.jpg',
        categories: ['children'],
      },
      {
        id: 6,
        title: 'Organic Silk Sheet Set',
        href: 'organic-silk-sheet-set',
        description: 'GOTS certified organic silk sheets',
        image: '/images/products/organic-1.jpg',
        categories: ['hotel'],
      },
      {
        id: 7,
        title: 'Hotel Collection Duvet',
        href: 'hotel-collection-duvet',
        description: 'Premium hotel quality silk duvet',
        image: '/images/products/hotel-1.jpg',
        categories: ['hotel'],
      },
      {
        id: 8,
        title: 'Summer Silk Throw',
        href: 'summer-silk-throw',
        description: 'Light silk throw for summer evenings',
        image: '/images/products/throw-1.jpg',
        categories: ['summer'],
      }
    ]